# Generated by Django 4.1.1 on 2022-10-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('once_off', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expiry', models.DateField()),
                ('user_id', models.BigIntegerField()),
            ],
        ),
    ]
