# Generated by Django 4.1.1 on 2022-10-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'service_category',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Beauty', 'Beauty'), ('Wellness', 'Wellness')], default='Wellness', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location_requirements', models.TextField()),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(null=True, upload_to='')),
                ('image3', models.ImageField(null=True, upload_to='')),
                ('duration', models.DurationField()),
                ('price', models.IntegerField()),
                ('max_recipients', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service_category')),
            ],
            options={
                'verbose_name': 'service',
                'db_table': 'mobile_service',
                'order_with_respect_to': 'type',
            },
        ),
    ]
