# Generated by Django 4.1.1 on 2022-10-24 19:51

from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.service_category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.upload_to),
        ),
        migrations.AlterField(
            model_name='service',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.upload_to),
        ),
        migrations.AlterField(
            model_name='service',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.upload_to),
        ),
        migrations.AlterField(
            model_name='service',
            name='payment_options',
            field=models.CharField(choices=[('EFT-Card-Cash', 'Eftcard'), ('Cash', 'Cash')], default='EFT-Card-Cash', max_length=20),
        ),
    ]
