# Generated by Django 4.1.1 on 2022-11-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
