# Generated by Django 4.1.1 on 2022-11-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='featured',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='promo_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
