# Generated by Django 4.1.1 on 2022-11-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_category_image1_alter_service_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='featured',
            field=models.IntegerField(default=0),
        ),
    ]
