# Generated by Django 4.1.1 on 2022-11-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_service_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_category',
            old_name='image1',
            new_name='image',
        ),
    ]
