# Generated by Django 4.1.1 on 2022-11-05 11:50

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_rename_image1_service_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='promo_price',
            field=models.IntegerField(default=0),
        ),
    ]
