from django.urls import path
from . import views

urlpatterns = [path("request/<int:service_id>/", views.BookingRequestCreateView.as_view(), name="request"),
               path("list/", views.BookingRequestListView.as_view(), name="list"),
               path("view/<int:appointment_id>/",
                    views.BookingRequestDetailView.as_view(), name="view"),
               path("view/",
                    views.RequestListAdmindasboard.as_view(), name="view-latest"),
               path("schedule/", views.ScheduledBookings.as_view(), name='schedule'),
               path("update-reply/<int:appointment_id>/",
                    views.BookingRequestReplyView.as_view(), name="reply"),
               path("cancel/<int:appointment_id>/",
                    views.BookingRequestCancelView.as_view(), name="cancel"),
               path("reschedule/<int:appointment_id>/",
                    views.UserRescheduleView.as_view(), name="reschedule"),
               path("account/<int:user_id>/bookings/",
                    views.UserBookingRequestsView.as_view(), name="account-bookings"),
               path("account/<int:user_id>/bookings/<int:appointment_id>/",
                    views.UserBookingRequestDetailView.as_view(), name="account-detail-booking"),
               path("booked-slots/", views.BookedSlotsListView.as_view(),
                    name="booked-slots"),
               path("location/", views.AppLocationCreateView.as_view(),
                    name="location"),
               path("address/<int:user_id>/",
                    views.UserLocationView.as_view(), name='address'),
               path("requests-per-month/", views.RequestStats.as_view(),
                    name='requets-per-month'),
               path("income-for-month/", views.IncomeMonth.as_view(), name='income'),
               path("completed-requests/", views.CompleteRequests.as_view(),
                    name='requets-completed'),
               path("new-requests/", views.NewRequests().as_view(), name='new-requests'), ]
