# Generated by Django 4.1.1 on 2022-09-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_jeanmobile_bookinghours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='client',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(db_index=True, unique=True),
        ),
    ]
