# Generated by Django 4.1.1 on 2022-09-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_client_appointment_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['created_at']},
        ),
    ]
