# Generated by Django 4.1.1 on 2022-10-04 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookedslot_delete_bookinghours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 12, 15, 36, 454952, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedslot',
            name='appt_date',
            field=models.DateField(default=datetime.date(2022, 10, 11)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bookedslot',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bookedslot',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
