# Generated by Django 4.1.1 on 2022-10-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_appointment_paid_appointment_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(default='EFT-Card', max_length=25),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
