# Generated by Django 4.1.1 on 2022-10-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_status_alter_service_category_and_more'),
        ('bookings', '0010_appointment_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(to='services.service'),
        ),
    ]
