# Generated by Django 4.1.1 on 2022-10-27 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_name'),
        ('bookings', '0011_remove_appointment_service_appointment_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='services',
            new_name='booking',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='recipients',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.service')),
            ],
        ),
    ]
