# Generated by Django 4.1.1 on 2022-10-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_name'),
        ('bookings', '0012_rename_services_appointment_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking',
            field=models.ManyToManyField(to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
