# Generated by Django 4.1.1 on 2022-10-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_appointment_booking_alter_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name_of_service',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
