# Generated by Django 4.1.1 on 2022-10-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_name'),
        ('bookings', '0014_booking_name_of_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='name_of_service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ManyToManyField(to='services.service'),
        ),
    ]
