# Generated by Django 4.1.1 on 2022-10-27 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_alter_booking_service_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applocation',
            old_name='address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='applocation',
            name='surburb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.applocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applocation',
            name='country',
            field=models.CharField(default='South Africa', max_length=255, null=True),
        ),
    ]
