# Generated by Django 4.1.1 on 2022-10-30 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0020_rename_address_applocation_street_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('completedApps', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.applocation'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
