# Generated by Django 4.1.1 on 2022-11-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_appointmentstats_alter_appointment_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appt_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SCHEDULE', 'scheduled'), ('DECLINE', 'declined'), ('CANCEL', 'cancelled'), ('ACCEPT', 'accepted')], default='pending', max_length=10),
        ),
    ]
