# Generated by Django 4.1.1 on 2022-11-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_alter_appointment_appt_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentStats',
        ),
    ]
